# Generated by Django 5.2.7 on 2025-10-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Prestado', 'Prestado')], default='Libre', max_length=10),
        ),
    ]
